version: '3.8'

services:
  backend:
    build: ./backend
    container_name: bjtu-homework-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: bjtu-homework-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
